import 'package:flutter/material.dart';
import 'package:pretty_qr_code/pretty_qr_code.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../models/pet.dart';
import '../../models/medical_record.dart';
import '../../services/medical_service.dart';
import '../../services/pet_service.dart';
import '../../utils/theme.dart';
import 'pet_passport_scanner_screen.dart';

class PetPassportScreen extends StatefulWidget {
  final String petId;

  const PetPassportScreen({super.key, required this.petId});

  @override
  State<PetPassportScreen> createState() => _PetPassportScreenState();
}

class _PetPassportScreenState extends State<PetPassportScreen> {
  final MedicalService _medicalService = MedicalService();
  final PetService _petService = PetService();

  Pet? _pet;
  List<MedicalRecord> _vaccinations = [];
  List<MedicalRecord> _allergies = [];
  List<MedicalRecord> _medications = [];
  bool _isLoading = true;

  // Privacy settings
  bool _includeBasicInfo = true;
  bool _includeVaccinations = true;
  bool _includeMedications = true;
  bool _includeAllergies = true;
  bool _includeEmergencyContact = true;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    try {
      _pet = await _petService.getPet(widget.petId);
      _vaccinations = await _medicalService.getMedicalRecordsByType(
        widget.petId,
        MedicalRecordType.vaccination,
      );
      _allergies = await _medicalService.getMedicalRecordsByType(
        widget.petId,
        MedicalRecordType.allergy,
      );
      _medications = await _medicalService.getActiveMedications(widget.petId);
    } catch (e) {
      // Handle error silently
    }
    setState(() => _isLoading = false);
  }

  String _generatePassportData() {
    if (_pet == null) return '';

    final buffer = StringBuffer();
    buffer.writeln('=== PET PASSPORT ===');
    buffer.writeln('Generated by PawPal');
    buffer.writeln('');

    if (_includeBasicInfo) {
      buffer.writeln('--- BASIC INFO ---');
      buffer.writeln('Name: ${_pet!.name}');
      buffer.writeln('Species: ${_pet!.species}');
      if (_pet!.breed != null) buffer.writeln('Breed: ${_pet!.breed}');
      buffer.writeln('Gender: ${_pet!.gender}');
      buffer.writeln('Age: ${_pet!.ageDisplay}');
      if (_pet!.microchipNumber != null) {
        buffer.writeln('Microchip: ${_pet!.microchipNumber}');
      }
      buffer.writeln('');
    }

    if (_includeVaccinations && _vaccinations.isNotEmpty) {
      buffer.writeln('--- VACCINATIONS ---');
      for (final vax in _vaccinations.take(5)) {
        buffer.writeln(
          '${vax.title}: ${DateFormat('MM/dd/yyyy').format(vax.date)}',
        );
        if (vax.nextDueDate != null) {
          buffer.writeln(
            '  Next due: ${DateFormat('MM/dd/yyyy').format(vax.nextDueDate!)}',
          );
        }
      }
      buffer.writeln('');
    }

    if (_includeMedications && _medications.isNotEmpty) {
      buffer.writeln('--- CURRENT MEDICATIONS ---');
      for (final med in _medications.take(5)) {
        buffer.write(med.title);
        if (med.dosage != null) buffer.write(' - ${med.dosage}');
        if (med.frequency != null) buffer.write(' (${med.frequency})');
        buffer.writeln('');
      }
      buffer.writeln('');
    }

    if (_includeAllergies && _allergies.isNotEmpty) {
      buffer.writeln('--- ALLERGIES ---');
      for (final allergy in _allergies) {
        buffer.writeln('• ${allergy.title}');
      }
      buffer.writeln('');
    }

    if (_includeEmergencyContact) {
      buffer.writeln('--- EMERGENCY CONTACT ---');
      buffer.writeln('Contact pet owner via PawPal app');
      buffer.writeln('');
    }

    buffer.writeln(
      'Updated: ${DateFormat('MM/dd/yyyy').format(DateTime.now())}',
    );

    return buffer.toString();
  }

  void _sharePassport() {
    if (_pet == null) return;
    final passportData = _generatePassportData();
    Share.share(passportData, subject: '${_pet!.name}\'s Pet Passport');
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Pet Passport')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    if (_pet == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Pet Passport')),
        body: const Center(child: Text('Pet not found')),
      );
    }

    final passportData = _generatePassportData();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Pet Passport'),
        actions: [
          IconButton(
            icon: const Icon(Icons.qr_code_scanner_rounded),
            tooltip: 'Scan pet passport',
            onPressed: () {
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (context) => const PetPassportScannerScreen(),
                ),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.share),
            tooltip: 'Share pet passport',
            onPressed: _sharePassport,
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Passport Card
            Container(
              decoration: BoxDecoration(
                color: AppTheme.cardBackground(context),
                borderRadius: BorderRadius.circular(32),
                border: AppTheme.borderFor(context),
                boxShadow: AppTheme.shadowFor(context),
              ),
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  children: [
                    // Header
                    Row(
                      children: [
                        Container(
                          width: 60,
                          height: 60,
                          decoration: BoxDecoration(
                            color: AppTheme.primaryColor.withValues(alpha: 0.1),
                            borderRadius: BorderRadius.circular(15),
                          ),
                          child: const Icon(
                            Icons.pets,
                            color: AppTheme.primaryColor,
                            size: 30,
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                _pet!.name,
                                style: const TextStyle(
                                  fontSize: 24,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                              Text(
                                '${_pet!.species}${_pet!.breed != null ? ' • ${_pet!.breed}' : ''}',
                                style: TextStyle(
                                  color: AppTheme.secondaryText(context),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),

                    // QR Code
                    Semantics(
                      label:
                          'QR code containing ${_pet!.name}\'s passport information',
                      image: true,
                      child: Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(color: AppTheme.divider(context)),
                        ),
                        child: SizedBox(
                          width: 200,
                          height: 200,
                          child: PrettyQrView.data(
                            data: passportData,
                            decoration: const PrettyQrDecoration(
                              shape: PrettyQrSmoothSymbol(),
                              background: Color(0xFFFFFFFF),
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Scan to view pet information',
                      style: TextStyle(
                        color: AppTheme.secondaryText(context),
                        fontSize: 14,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 24),

            // Privacy Settings
            const Text(
              'Information to Include',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            Container(
              decoration: BoxDecoration(
                color: AppTheme.cardBackground(context),
                borderRadius: BorderRadius.circular(32),
                border: AppTheme.borderFor(context),
                boxShadow: AppTheme.shadowFor(context),
              ),
              child: Column(
                children: [
                  SwitchListTile(
                    title: const Text('Basic Information'),
                    subtitle: const Text('Name, species, breed, age'),
                    value: _includeBasicInfo,
                    onChanged: (value) {
                      setState(() => _includeBasicInfo = value);
                    },
                  ),
                  const Divider(height: 1),
                  SwitchListTile(
                    title: const Text('Vaccinations'),
                    subtitle: Text(
                      _vaccinations.isEmpty
                          ? 'No vaccinations recorded'
                          : '${_vaccinations.length} vaccination(s)',
                    ),
                    value: _includeVaccinations,
                    onChanged: _vaccinations.isEmpty
                        ? null
                        : (value) {
                            setState(() => _includeVaccinations = value);
                          },
                  ),
                  const Divider(height: 1),
                  SwitchListTile(
                    title: const Text('Current Medications'),
                    subtitle: Text(
                      _medications.isEmpty
                          ? 'No active medications'
                          : '${_medications.length} medication(s)',
                    ),
                    value: _includeMedications,
                    onChanged: _medications.isEmpty
                        ? null
                        : (value) {
                            setState(() => _includeMedications = value);
                          },
                  ),
                  const Divider(height: 1),
                  SwitchListTile(
                    title: const Text('Allergies'),
                    subtitle: Text(
                      _allergies.isEmpty
                          ? 'No allergies recorded'
                          : '${_allergies.length} allergy/allergies',
                    ),
                    value: _includeAllergies,
                    onChanged: _allergies.isEmpty
                        ? null
                        : (value) {
                            setState(() => _includeAllergies = value);
                          },
                  ),
                  const Divider(height: 1),
                  SwitchListTile(
                    title: const Text('Emergency Contact'),
                    subtitle: const Text('Link to contact owner'),
                    value: _includeEmergencyContact,
                    onChanged: (value) {
                      setState(() => _includeEmergencyContact = value);
                    },
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Share buttons
            ElevatedButton.icon(
              onPressed: _sharePassport,
              icon: const Icon(Icons.share),
              label: const Text('Share Pet Passport'),
            ),
            const SizedBox(height: 12),
            OutlinedButton.icon(
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => const PetPassportScannerScreen(),
                  ),
                );
              },
              icon: const Icon(Icons.qr_code_scanner_rounded),
              label: const Text('Scan a Pet Passport'),
            ),
            const SizedBox(height: 12),
            OutlinedButton.icon(
              onPressed: () {
                final passportText = _generatePassportData();
                Share.share(
                  passportText,
                  subject: '${_pet!.name}\'s Pet Passport',
                );
              },
              icon: const Icon(Icons.picture_as_pdf),
              label: const Text('Export as PDF'),
            ),
            const SizedBox(height: 24),

            // Preview
            const Text(
              'Preview',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            Container(
              decoration: BoxDecoration(
                color: AppTheme.cardBackground(context),
                borderRadius: BorderRadius.circular(24),
                border: AppTheme.borderFor(context),
                boxShadow: AppTheme.shadowFor(context),
              ),
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Text(
                  passportData,
                  style: const TextStyle(fontFamily: 'monospace', fontSize: 12),
                ),
              ),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }
}
