import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:share_plus/share_plus.dart';
import '../../utils/theme.dart';

class PetPassportScannerScreen extends StatefulWidget {
  const PetPassportScannerScreen({super.key});

  @override
  State<PetPassportScannerScreen> createState() =>
      _PetPassportScannerScreenState();
}

class _PetPassportScannerScreenState extends State<PetPassportScannerScreen> {
  late final MobileScannerController _controller;
  String? _scannedData;
  bool _isProcessing = false;

  @override
  void initState() {
    super.initState();
    _controller = MobileScannerController(
      detectionSpeed: DetectionSpeed.noDuplicates,
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _handleDetect(BarcodeCapture capture) {
    if (_isProcessing || _scannedData != null) return;

    final values = capture.barcodes
        .map((barcode) => barcode.rawValue)
        .whereType<String>()
        .where((value) => value.trim().isNotEmpty);
    final value = values.isEmpty ? null : values.first;

    if (value == null) return;

    setState(() {
      _isProcessing = true;
      _scannedData = value.trim();
    });
    _controller.stop();
  }

  void _scanAgain() {
    setState(() {
      _scannedData = null;
      _isProcessing = false;
    });
    _controller.start();
  }

  Future<void> _pastePassportText() async {
    final controller = TextEditingController();

    final value = await showDialog<String>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: Text('Paste Passport QR Data'),
          content: TextField(
            controller: controller,
            minLines: 5,
            maxLines: 10,
            decoration: const InputDecoration(
              hintText: 'Paste the text from a PawPal passport QR code',
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.of(context).pop(controller.text),
              child: Text('Preview'),
            ),
          ],
        );
      },
    );

    controller.dispose();
    final trimmed = value?.trim();
    if (trimmed == null || trimmed.isEmpty) return;

    setState(() {
      _isProcessing = true;
      _scannedData = trimmed;
    });
    await _controller.stop();
  }

  String? _extractLine(String label) {
    final data = _scannedData;
    if (data == null) return null;
    final prefix = '$label:';

    for (final line in data.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.toLowerCase().startsWith(prefix.toLowerCase())) {
        return trimmed.substring(prefix.length).trim();
      }
    }

    return null;
  }

  bool get _isPawPalPassport {
    final data = _scannedData;
    return data != null &&
        data.contains('=== PET PASSPORT ===') &&
        data.contains('Generated by PawPal');
  }

  @override
  Widget build(BuildContext context) {
    final scannedData = _scannedData;

    return Scaffold(
      appBar: AppBar(
        title: Text('Scan Pet Passport'),
        actions: [
          IconButton(
            tooltip: 'Paste passport data',
            onPressed: _pastePassportText,
            icon: const Icon(Icons.content_paste_rounded),
          ),
        ],
      ),
      body: scannedData == null ? _buildScanner() : _buildResult(scannedData),
    );
  }

  Widget _buildScanner() {
    return ListView(
      padding: const EdgeInsets.fromLTRB(24, 16, 24, 120),
      children: [
        Container(
          height: 360,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: Colors.black,
            borderRadius: BorderRadius.circular(28),
            border: AppTheme.borderFor(context),
            boxShadow: AppTheme.shadowFor(context),
          ),
          child: Stack(
            fit: StackFit.expand,
            children: [
              MobileScanner(controller: _controller, onDetect: _handleDetect),
              Center(
                child: Container(
                  width: 220,
                  height: 220,
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.white, width: 3),
                    borderRadius: BorderRadius.circular(24),
                  ),
                ),
              ),
            ],
          ),
        ),
        const SizedBox(height: 24),
        Text(
          'Point your camera at a PawPal pet passport QR code.',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: AppTheme.secondaryText(context),
            fontSize: 16,
            fontWeight: FontWeight.w600,
          ),
        ),
        const SizedBox(height: 16),
        OutlinedButton.icon(
          onPressed: _pastePassportText,
          icon: const Icon(Icons.content_paste_rounded),
          label: Text('Paste QR Data'),
        ),
      ],
    );
  }

  Widget _buildResult(String scannedData) {
    final petName = _extractLine('Name');
    final species = _extractLine('Species');
    final updated = _extractLine('Updated');

    return ListView(
      padding: const EdgeInsets.fromLTRB(24, 16, 24, 120),
      children: [
        Container(
          padding: const EdgeInsets.all(24),
          decoration: BoxDecoration(
            color: AppTheme.cardBackground(context),
            borderRadius: BorderRadius.circular(28),
            border: AppTheme.borderFor(context),
            boxShadow: AppTheme.shadowFor(context),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color:
                          (_isPawPalPassport
                                  ? AppTheme.secondaryColor
                                  : AppTheme.accentColor)
                              .withValues(alpha: 0.12),
                      borderRadius: BorderRadius.circular(18),
                    ),
                    child: Icon(
                      _isPawPalPassport
                          ? Icons.verified_rounded
                          : Icons.qr_code_rounded,
                      color: _isPawPalPassport
                          ? AppTheme.secondaryColor
                          : AppTheme.accentColor,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          petName ?? 'Scanned QR Code',
                          style: TextStyle(
                            color: AppTheme.primaryText(context),
                            fontSize: 22,
                            fontWeight: FontWeight.w800,
                          ),
                        ),
                        if (species != null)
                          Text(
                            species,
                            style: TextStyle(
                              color: AppTheme.secondaryText(context),
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                      ],
                    ),
                  ),
                ],
              ),
              if (updated != null) ...[
                const SizedBox(height: 16),
                Text(
                  'Updated $updated',
                  style: TextStyle(color: AppTheme.mutedText(context)),
                ),
              ],
            ],
          ),
        ),
        const SizedBox(height: 20),
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: AppTheme.cardBackground(context),
            borderRadius: BorderRadius.circular(20),
            border: AppTheme.borderFor(context),
          ),
          child: SelectableText(
            scannedData,
            style: TextStyle(fontFamily: 'monospace', fontSize: 13),
          ),
        ),
        const SizedBox(height: 20),
        Row(
          children: [
            Expanded(
              child: OutlinedButton.icon(
                onPressed: _scanAgain,
                icon: const Icon(Icons.qr_code_scanner_rounded),
                label: Text('Scan Again'),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: FilledButton.icon(
                onPressed: () => Share.share(scannedData),
                icon: const Icon(Icons.share_rounded),
                label: Text('Share'),
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        TextButton.icon(
          onPressed: () {
            Clipboard.setData(ClipboardData(text: scannedData));
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Passport data copied')),
            );
          },
          icon: const Icon(Icons.copy_rounded),
          label: Text('Copy Data'),
        ),
      ],
    );
  }
}
